-- H2 2.4.240;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT 'a486cc53396e9dc8' HASH 'fc5c0f6feff9f38a6bc2e400bc15abbbe5c6d750c5564d7d44da1d6b1b3e803c' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."EPISODES"(
    "ADDED_DATE" DATE,
    "AUDIO_QUALITY" INTEGER,
    "BOOKMARKED_QUOTE" BOOLEAN NOT NULL,
    "CONTENT_QUALITY" INTEGER,
    "DURATION_MINUTES" INTEGER,
    "EXPLICIT_CONTENT" BOOLEAN NOT NULL,
    "HOST_CHEMISTRY" INTEGER,
    "LISTENED_DATE" DATE,
    "MINUTES_LISTENED" INTEGER,
    "RATING" INTEGER,
    "RECOMMEND_TO_FRIEND" BOOLEAN NOT NULL,
    "RELEASE_DATE" DATE,
    "REWATCH_VALUE" INTEGER,
    "SEASON_NUMBER" INTEGER,
    "SUBSCRIBED" BOOLEAN NOT NULL,
    "ADDED_BY_ID" BIGINT,
    "CREATED_AT" TIMESTAMP(6),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 11) NOT NULL,
    "UPDATED_AT" TIMESTAMP(6),
    "EPISODE_NUMBER" CHARACTER VARYING(30),
    "NETWORK" CHARACTER VARYING(50),
    "MAIN_TOPIC" CHARACTER VARYING(100),
    "HOSTS" CHARACTER VARYING(200) NOT NULL,
    "MOOD_TAGS" CHARACTER VARYING(200),
    "SHOW_NAME" CHARACTER VARYING(200) NOT NULL,
    "TITLE" CHARACTER VARYING(250) NOT NULL,
    "GUESTS" CHARACTER VARYING(300),
    "KEY_TAKEAWAY" CHARACTER VARYING(300),
    "MEMORABLE_QUOTE" CHARACTER VARYING(500),
    "PERSONAL_NOTES" CHARACTER VARYING(2000),
    "REVIEW" CHARACTER VARYING(2000),
    "CATEGORY" ENUM('BUSINESS', 'COMEDY', 'EDUCATION', 'HEALTH_WELLNESS', 'HISTORY', 'INTERVIEW', 'MENTAL_HEALTH', 'NEWS_POLITICS', 'POP_CULTURE', 'SCIENCE', 'SOCIETY_CULTURE', 'SPORTS', 'STORYTELLING', 'TECHNOLOGY', 'TRUE_CRIME') NOT NULL,
    "LISTENING_CONTEXT" ENUM('BACKGROUND', 'COMMUTE', 'COOKING', 'FOCUSED_LISTEN', 'HOUSEWORK', 'SLEEP', 'WALKING', 'WORKOUT'),
    "PLAYBACK_SPEED" ENUM('SPEED_0_75X', 'SPEED_1_0X', 'SPEED_1_25X', 'SPEED_1_5X', 'SPEED_1_75X', 'SPEED_2_0X'),
    "STATUS" ENUM('FINISHED', 'LISTENING', 'QUEUED', 'SAVED_FOR_LATER', 'SKIPPED') NOT NULL
);           
ALTER TABLE "PUBLIC"."EPISODES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8EBF1D8_1" PRIMARY KEY("ID");             
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.EPISODES;               
INSERT INTO "PUBLIC"."EPISODES" VALUES
(DATE '2025-10-28', 9, TRUE, 10, 92, FALSE, 10, DATE '2025-11-05', 92, 5, TRUE, DATE '2025-11-04', 9, 3, TRUE, 1, TIMESTAMP '2026-06-28 21:17:10.212555', 1, TIMESTAMP '2026-06-28 21:17:10.212555', 'S3E12', 'Spotify', 'Wellness industry, weight loss myths, junk science', 'Aubrey Gordon, Michael Hobbes', 'Investigative, sharp, devastating in the best way', 'Maintenance Phase', 'The Wellness Industrial Complex', NULL, 'Health is a social construct, weight is not a measure of worth', 'The wellness industry isn''t selling you health, it''s selling you the anxiety that you don''t have it.', NULL, 'Aubrey and Michael are the only ones who debunk wellness grifters this thoroughly. Listened on my Tuesday commute, missed my stop because I was too invested.Recommended to everyone. Their backlog is gold.', 'HEALTH_WELLNESS', 'COMMUTE', 'SPEED_1_25X', 'FINISHED'),
(DATE '2025-10-20', 8, TRUE, 9, 78, FALSE, 10, DATE '2025-10-25', 78, 5, TRUE, DATE '2025-10-22', 8, NULL, TRUE, 1, TIMESTAMP '2026-06-28 21:17:10.26305', 2, TIMESTAMP '2026-06-28 21:17:10.26305', 'EP 178', 'Spotify', 'Reality TV history, 2003 culture, prank shows', 'Sarah Marshall', 'Nostalgic deep-dive, cozy, hilarious analysis', 'You''re Wrong About', 'The Joe Schmo Show Phenomenon', 'Blair Braverman', 'Reality TV is more constructed than fiction', 'We treat the past like another country, but it''s really just a place where we used to live.', NULL, 'Sarah Marshall makes EVERYTHING interesting. The Joe Schmo show analysis was genuinely revelatory. I love how she finds the humanity in trash TV.Sarah''s takes are always thoughtful. Subscribed for years.', 'SOCIETY_CULTURE', 'HOUSEWORK', 'SPEED_1_5X', 'FINISHED'),
(DATE '2025-09-14', 9, FALSE, 8, 71, TRUE, 10, DATE '2025-09-16', 71, 4, TRUE, DATE '2025-09-15', 6, NULL, TRUE, 1, TIMESTAMP '2026-06-28 21:17:10.269106', 3, TIMESTAMP '2026-06-28 21:17:10.269106', 'EP 287', 'Plosive Productions', 'Food preferences, hospitality, comedy podcast format', 'Ed Gamble, James Acaster', 'Pure chaos, dream restaurant format, British wit', 'Off Menu', 'Annie Mac on Hosting Cool Girl Energy', 'Annie Mac', 'The best comedy comes from genuine specificity', 'Welcome to The Dream Restaurant.', NULL, 'James Acaster''s absolute commitment to the bit is a national treasure. Annie Mac was a perfect guest. I listened during my evening walk and got weird looks for laughing alone.Comfort listen. Their dynamic is unmatched.', 'COMEDY', 'WALKING', 'SPEED_1_0X', 'FINISHED'),
(DATE '2026-05-02', NULL, FALSE, NULL, 134, TRUE, NULL, NULL, 67, NULL, FALSE, DATE '2026-05-01', NULL, NULL, TRUE, 1, TIMESTAMP '2026-06-28 21:17:10.275164', 4, TIMESTAMP '2026-06-28 21:17:10.275164', 'EP 590', 'Spotify', 'Columbine, religious mythology, school shootings', 'Marcus Parks, Henry Zebrowski, Ed Larson', 'Heavy material, well-researched, dark humor balance', 'Last Podcast on the Left', 'Episode 1: Cassie Bernall', NULL, NULL, NULL, NULL, 'Half-way through. Their Columbine series is heavy. Listening during workouts to dilute the intensity.', 'TRUE_CRIME', 'WORKOUT', 'SPEED_1_5X', 'LISTENING'),
(DATE '2025-12-01', 10, TRUE, 10, 58, FALSE, 9, DATE '2025-12-07', 58, 5, TRUE, DATE '2025-12-03', 8, NULL, TRUE, 1, TIMESTAMP '2026-06-28 21:17:10.281879', 5, TIMESTAMP '2026-06-28 21:17:10.281879', 'EP 412', 'Hidden Brain Media', 'Dopamine, addiction, screen time, behavioral psychology', 'Shankar Vedantam', 'Soothing, science-backed, paradigm-shifting', 'Hidden Brain', 'How To Stop Doomscrolling', 'Dr. Anna Lembke', 'Dopamine fasting actually works, your phone is the problem', 'The relentless pursuit of pleasure leads to pain. The deliberate pursuit of pain leads to pleasure.', NULL, 'Anna Lembke''s book Dopamine Nation rewired my brain and this episode was a perfect intro. Shankar''s voice is the most calming thing in audio.Listen before bed. Deleted TikTok for a week after this.', 'SCIENCE', 'SLEEP', 'SPEED_1_0X', 'FINISHED'),
(DATE '2026-04-01', NULL, FALSE, NULL, 245, FALSE, NULL, NULL, 0, NULL, FALSE, DATE '2026-03-20', NULL, 15, TRUE, 1, TIMESTAMP '2026-06-28 21:17:10.288515', 6, TIMESTAMP '2026-06-28 21:17:10.288515', 'S15E4', 'Acquired LLC', 'Startup management, founder vs manager mode, Airbnb', 'Ben Gilbert, David Rosenthal', NULL, 'Acquired', 'The Founder''s Mode Phenomenon', 'Brian Chesky', NULL, NULL, NULL, 'Saved for a long flight. 4+ hour episodes are an Acquired signature. Brian Chesky has been everywhere this year.', 'BUSINESS', NULL, NULL, 'SAVED_FOR_LATER');              
INSERT INTO "PUBLIC"."EPISODES" VALUES
(DATE '2025-07-12', 9, FALSE, 7, 178, FALSE, 7, DATE '2025-07-18', 178, 3, FALSE, DATE '2025-07-14', 5, NULL, FALSE, 1, TIMESTAMP '2026-06-28 21:17:10.295947', 7, TIMESTAMP '2026-06-28 21:17:10.295947', 'EP 195', 'Scicomm Media', 'Stoicism, ancient philosophy, modern life', 'Andrew Huberman', 'Bro philosophy, dense, occasionally insightful', 'Huberman Lab', 'Anyone Can Be A Stoic', 'Ryan Holiday', 'Stoicism without the marketing is just discipline', 'You don''t rise to the level of your goals, you fall to the level of your systems.', NULL, 'Listened at 2x because Huberman''s pacing is glacial. Ryan Holiday has good points but the bro-coded delivery is exhausting. 3 stars max.Not subscribing. One was enough.', 'HEALTH_WELLNESS', 'WORKOUT', 'SPEED_2_0X', 'FINISHED'),
(DATE '2026-01-05', 9, TRUE, 10, 62, FALSE, 10, DATE '2026-01-10', 62, 5, TRUE, DATE '2026-01-08', 9, 5, TRUE, 1, TIMESTAMP '2026-06-28 21:17:10.295947', 8, TIMESTAMP '2026-06-28 21:17:10.295947', 'S5E1', 'Defector Media', 'Gossip culture, relationship drama, anonymous stories', 'Kelsey McKinney', 'Anonymous gossip, sapphic chaos, perfect format', 'Normal Gossip', 'Episode 1: We''re All Going to the Olympics', 'Connor Franta', 'The best stories are real stories from regular people', 'Friend, this story has so many twists I am going to need to lie down.', NULL, 'Kelsey McKinney''s gasps are the soundtrack of my life. The Olympics story was UNHINGED in the best way. I literally screamed at my pasta sauce.Comfort listen. Sundays are for Normal Gossip and dinner prep.', 'STORYTELLING', 'COOKING', 'SPEED_1_25X', 'FINISHED'),
(DATE '2026-05-01', NULL, FALSE, NULL, 54, FALSE, NULL, NULL, 0, NULL, FALSE, DATE '2026-04-28', NULL, NULL, FALSE, 1, TIMESTAMP '2026-06-28 21:17:10.304391', 9, TIMESTAMP '2026-06-28 21:17:10.304391', 'EP 67', 'Odyssey', 'Dating apps, modern romance, tech criticism', 'PJ Vogt', NULL, 'Search Engine', 'How Tinder Killed The Meet Cute', NULL, NULL, NULL, NULL, 'PJ Vogt''s voice can read me the phone book. In my queue for tomorrow''s commute.', 'TECHNOLOGY', NULL, NULL, 'QUEUED'),
(DATE '2024-12-14', 8, FALSE, 5, 132, FALSE, 3, DATE '2024-12-20', 28, 2, FALSE, DATE '2024-12-14', 2, NULL, FALSE, 1, TIMESTAMP '2026-06-28 21:17:10.304391', 10, TIMESTAMP '2026-06-28 21:17:10.304391', 'EP 405', 'Lex Fridman Productions', 'Amazon, space exploration, productivity', 'Lex Fridman', 'Long-winded, hagiographic, surface-level', 'Lex Fridman Podcast', 'Lex Speaks With Jeff Bezos', 'Jeff Bezos', 'Lex needs to push back more on his guests', NULL, NULL, 'Skipped at 28 minutes. Lex''s interviews have become uncritical CEO infomercials. The whole tech-bro philosophical performance gets old fast.Probably done with this show. Used to be good circa episode 100.', 'INTERVIEW', 'BACKGROUND', 'SPEED_1_75X', 'SKIPPED');               
CREATE MEMORY TABLE "PUBLIC"."REFRESH_TOKENS"(
    "REVOKED" BOOLEAN NOT NULL,
    "EXPIRY_DATE" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "USER_ID" BIGINT NOT NULL,
    "TOKEN" CHARACTER VARYING(512) NOT NULL
);            
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C4C" PRIMARY KEY("ID");             
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.REFRESH_TOKENS;          
INSERT INTO "PUBLIC"."REFRESH_TOKENS" VALUES
(FALSE, TIMESTAMP WITH TIME ZONE '2026-07-05 19:23:54.986611+00', 2, 1, '44ea349c-ed7c-4a79-9aa6-50e2039f96e8');
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "ENABLED" BOOLEAN NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "REGISTERED_AT" TIMESTAMP(6) NOT NULL,
    "USERNAME" CHARACTER VARYING(50) NOT NULL,
    "EMAIL" CHARACTER VARYING(100) NOT NULL,
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "ROLE" ENUM('ADMIN', 'USER') NOT NULL
);     
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D4" PRIMARY KEY("ID");      
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
INSERT INTO "PUBLIC"."USERS" VALUES
(TRUE, 1, TIMESTAMP '2026-06-28 21:17:09.91272', 'admin', 'admin@podcast.hr', '$2a$10$TD0r1xdaWWaeLsRD8TZ7/uvRaZt9VP0xzel2f493FsqX37MV7kkRq', 'ADMIN'),
(TRUE, 2, TIMESTAMP '2026-06-28 21:17:10.212555', 'user', 'user@podcast.hr', '$2a$10$j03JN9zfTi9FFdXl4Uo1muhxRuYlFN8KNCB42jbelSreVfOKfinqi', 'USER');           
ALTER TABLE "PUBLIC"."EPISODES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8EBF1" CHECK(("MINUTES_LISTENED" <= 900)
    AND ("MINUTES_LISTENED" >= 0)) NOCHECK;     
ALTER TABLE "PUBLIC"."EPISODES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8E" CHECK(("CONTENT_QUALITY" >= 1)
    AND ("CONTENT_QUALITY" <= 10)) NOCHECK;           
ALTER TABLE "PUBLIC"."EPISODES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8EBF" CHECK(("HOST_CHEMISTRY" >= 1)
    AND ("HOST_CHEMISTRY" <= 10)) NOCHECK;           
ALTER TABLE "PUBLIC"."EPISODES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8EBF1D" CHECK(("RATING" <= 5)
    AND ("RATING" >= 1)) NOCHECK;          
ALTER TABLE "PUBLIC"."EPISODES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8EB" CHECK(("DURATION_MINUTES" <= 900)
    AND ("DURATION_MINUTES" >= 1)) NOCHECK;       
ALTER TABLE "PUBLIC"."EPISODES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" CHECK(("AUDIO_QUALITY" >= 1)
    AND ("AUDIO_QUALITY" <= 10)) NOCHECK;
ALTER TABLE "PUBLIC"."EPISODES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8EBF1D8" CHECK(("REWATCH_VALUE" >= 1)
    AND ("REWATCH_VALUE" <= 10)) NOCHECK;          
ALTER TABLE "PUBLIC"."EPISODES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8EBF1D8_0" CHECK(("SEASON_NUMBER" <= 50)
    AND ("SEASON_NUMBER" >= 1)) NOCHECK;        
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" UNIQUE NULLS DISTINCT ("USERNAME");       
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" UNIQUE NULLS DISTINCT ("USER_ID");               
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C4" UNIQUE NULLS DISTINCT ("TOKEN");
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" UNIQUE NULLS DISTINCT ("EMAIL");         
ALTER TABLE "PUBLIC"."EPISODES" ADD CONSTRAINT "PUBLIC"."FK38IHPN85MLTBSBWFJOBGPB0AG" FOREIGN KEY("ADDED_BY_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."FK1LIH5Y2NPSF8U5O3VHDB9Y0OS" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK; 
