{
 "title": "Podcast",
 "tags": [
  "camel",
  "podcast"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Episode requests processed (total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podcast_episodes_processed_total{application=\"podcast-camel\"})"
    }
   ]
  },
  {
   "title": "Episode activities processed (total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(podcast_episode_activities_processed_total{application=\"podcast-camel\"})"
    }
   ]
  },
  {
   "title": "Episode publications processed (total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(podcast_episode_publications_processed_total{application=\"podcast-camel\"})"
    }
   ]
  },
  {
   "title": "Duplicate publications blocked (total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(podcast_duplicates_blocked_total{application=\"podcast-camel\"})"
    }
   ]
  },
  {
   "title": "Podcast Camel exchanges processed (rate / sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(camel_exchanges_succeeded_total{application=\"podcast-camel\"}[1m])) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Podcast Camel exchange failures (rate / sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(camel_exchanges_failed_total{application=\"podcast-camel\"}[1m])) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  }
 ]
}